// Generated by eve. Do not edit by hand.
import { POST } from "./workflows.mjs";
import { getWorld as __eveGetWorkflowWorld } from "/Users/bharath/dev/nominee/node_modules/.pnpm/eve@0.11.7_@opentelemetry+api@1.9.1_ai@7.0.0-beta.178_zod@4.4.3__chokidar@4.0.3_dotenv@_5cbd5fbc9c245e30c0b6954c8152b043/node_modules/eve/dist/src/compiled/@workflow/core/runtime.js";

try {
  const __eveWorkflowWorld = await __eveGetWorkflowWorld();
  if (typeof __eveWorkflowWorld?.registerHandler === "function") {
    __eveWorkflowWorld.registerHandler("__eve_wkf_workflow_", POST);
  }
} catch (err) {
  console.warn("[eve] Failed to register direct workflow queue handlers:", err);
}

export default async ({ req }) => {
  return await POST(req);
};
