// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/tools/merge_pr_naive.ts";
import * as module_2 from "../../agent/tools/merge_pr.ts";
import * as module_3 from "../../agent/tools/review_pr.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "tools/merge_pr_naive.ts": module_1,
                  "tools/merge_pr.ts": module_2,
                  "tools/review_pr.ts": module_3
                })
            })
    })
});

export default moduleMap;
